export const products =  [
    {
        bestSeller: true,
        totalServings: 7,
        rating: 4.91,
        proteinName: "Daily Plant Protein",
        flavour: "Chocolate",
        productPrice: 875,
        discountedPrice: 770,
        offerPercentage: 12,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/Jar-Chocolate-Listing-opt-400x400.png"
    },
    {
        bestSeller: true,
        totalServings: 20,
        rating: 4.75,
        proteinName: "Daily Plant Protein",
        flavour: "Chocolate",
        productPrice: 2200,
        discountedPrice: 1936,
        offerPercentage: 12,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/choco-pack-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 7,
        rating: 4.7,
        proteinName: "Daily Plant Protein",
        flavour: "Vanilla",
        productPrice: 875,
        discountedPrice: 744,
        offerPercentage: 15,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/Jar-Vanilla-Listing-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 20,
        rating: 4.75,
        proteinName: "Daily Plant Protein",
        flavour: "Vanilla",
        productPrice: 2200,
        discountedPrice: 1870,
        offerPercentage: 15,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/vanilla-pack-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 7,
        rating: 4.83,
        proteinName: "Daily Plant Protein",
        flavour: "Straberry",
        productPrice: 875,
        discountedPrice: 744,
        offerPercentage: 15,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/Jar-Strawberry-Listing-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 20,
        rating: 4.78,
        proteinName: "Daily Plant Protein",
        flavour: "Straberry",
        productPrice: 2200,
        discountedPrice: 1870,
        offerPercentage: 15,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/strawberry-pack-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 8,
        rating: 4.79,
        proteinName: "Daily Plant Protein",
        flavour: "Unflavoured",
        productPrice: 675,
        discountedPrice: 594,
        offerPercentage: 12,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/Jar-Unflavoured-Listing-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 32,
        rating: 4.78,
        proteinName: "Daily Plant Protein",
        flavour: "Unflavoured",
        productPrice: 2400,
        discountedPrice: 2112,
        offerPercentage: 12,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/unflavoured-pack-new-opt-400x400.png"
    },
    {
        bestSeller: false,
        totalServings: 7,
        rating: 4.83,
        proteinName: "Daily Plant Protein",
        flavour: "Mango mania",
        productPrice: 875,
        discountedPrice: 744,
        offerPercentage: 15,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/04/mango-jar-for-website-400x400.png"
    },
    {
        new: true,
        beginnersBox: true,
        bestSeller: false,
        totalServings: 3,
        rating: 5,
        proteinName: "Daily Plant Protein - Trial Pack",
        flavour: "Chocolate",
        productPrice: 425,
        discountedPrice: 383,
        offerPercentage: 10,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/12/mock1-1-400x400.png"
    },
    {
        new: false,
        beginnersBox: true,
        bestSeller: false,
        totalServings: 4,
        rating: 4.78,
        proteinName: "Daily Plant Protein - Trail Pack",
        flavour: "Multi Flavour",
        productPrice: 570,
        discountedPrice: 513,
        offerPercentage: 10,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2021/11/MF-Pack-mockup-Front-1--400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 7,
        rating: 4.89,
        proteinName: "Daily Plant Protein",
        flavour: "Coffee Caramel",
        productPrice: 875,
        discountedPrice: null,
        offerPercentage: null,
        outOfStock: true,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/Jar-Coffee-Listing-new-opt-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 20,
        rating: 4.75,
        proteinName: "Daily Plant Protein",
        flavour: "Coffee Caramel",
        productPrice: 2200,
        discountedPrice: 0,
        offerPercentage: 0,
        outOfStock: true,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/coffee-pack-new-opt-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 11,
        rating: 4.78,
        proteinName: "Go-Go Fuel for Kids (Ages 4-7)",
        flavour: "Champions Chocolates",
        productPrice: 849,
        discountedPrice: 747,
        offerPercentage: 12,
        outOfStock: false,
        trustedByMoms: true,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/04/choco-jar-4-7-website-1-1-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 10,
        rating: 4.86,
        proteinName: "Go-Go Fuel for Kids (Ages 8-12)",
        flavour: "Champions Chocolates",
        productPrice: 849,
        discountedPrice: 747,
        offerPercentage: 12,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/05/choco-jar-8-12-website-1-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 12,
        rating: 4.67,
        proteinName: "Go-Go Fuel for Kids (Ages 4-7)",
        flavour: "Vibrant Vanilla",
        productPrice: 849,
        discountedPrice: 747,
        offerPercentage: 12,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/04/van-jar-4-7-website-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 11,
        rating: 4.75,
        proteinName: "Go-Go Fuel for Kids (Ages 8-12)",
        flavour: "Vibrant Vanilla",
        productPrice: 849,
        discountedPrice: 747,
        offerPercentage: 12,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/04/van-jar-4-7-website-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 16,
        rating: 4.89,
        proteinName: "Vegan Protein for Senior Care",
        flavour: "Strawberry",
        productPrice: 1299,
        discountedPrice: 1143,
        offerPercentage: 12,
        outOfStock: false,
        SeniorsFriendly: true,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/02/senior-care-jar_New-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 15,
        rating: 4.9,
        proteinName: "Plant Based Biotin",
        flavour: "Strawberry Pineapple",
        productPrice: 699,
        discountedPrice: 594,
        offerPercentage: 15,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2022/07/Biotin-opt-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: 15,
        rating: 4.88,
        proteinName: "Super greens",
        flavour: "Green Apple Sorbet",
        productPrice: 699,
        discountedPrice: 594,
        offerPercentage: 15,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/02/supergreens-jar-1-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: null,
        rating: 5,
        shaker: "Origin 700ml Shaker",
        productPrice: 400,
        discountedPrice: 352,
        offerPercentage: 12,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2021/12/Untitled-design-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: null,
        rating: null,
        proteinChips: "Mojo Pops Protein Chips (6 Packs)",
        flavour: "Sour Cream & Onion",
        productPrice: 594,
        discountedPrice: null,
        offerPercentage: null,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/06/aCcaac-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: null,
        rating: 4,
        proteinChips: "Mojo Pops Protein Chips (6 Packs)",
        flavour: "Pudina Chutney",
        productPrice: 594,
        discountedPrice: null,
        offerPercentage: null,
        outOfStock: false,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/06/pudhina-product-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: null,
        rating: null,
        proteinChips: "Mojo Pops Protein Chips (6 Packs)",
        flavour: "Tangy Tomato",
        productPrice: 594,
        discountedPrice: null,
        offerPercentage: null,
        outOfStock: true,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/06/tomatp-product-page-400x400.png"
    },
    {
        new: false,
        beginnersBox: false,
        bestSeller: false,
        totalServings: null,
        rating: 4.67,
        proteinChips: "Mojo Pops Protein Chips (6 Packs)",
        flavour: "Assorted Pack",
        productPrice: 594,
        discountedPrice: null,
        offerPercentage: null,
        outOfStock: true,
        trustedByMoms: false,
        imagesProducts:"https://cdn.shortpixel.ai/spai/q_lossy+ex_1+ret_img+to_webp/https://originnutrition.in/wp-content/uploads/2023/06/listing-pack-5-400x401.png"
    }
]